const bookMapping = {
    "Jenèz": { fr: "Genèse", es: "Génesis" },
    "Egzòd": { fr: "Exode", es: "Éxodo" },
    "Levitik": { fr: "Lévitique", es: "Levítico" },
    "Nonb": { fr: "Nombres", es: "Números" },
    "Detewonòm": { fr: "Deutéronome", es: "Deuteronomio" },
    "Jozye": { fr: "Josué", es: "Josué" },
    "Jij": { fr: "Juges", es: "Jueces" },
    "Rit": { fr: "Ruth", es: "Rut" },
    "1 Samyèl": { fr: "1 Samuel", es: "1 Samuel" },
    "2 Samyèl": { fr: "2 Samuel", es: "2 Samuel" },
    "1 Wa": { fr: "1 Rois", es: "1 Reyes" },
    "2 Wa": { fr: "2 Rois", es: "2 Reyes" },
    "1 Kwonik": { fr: "1 Chroniques", es: "1 Crónicas" },
    "2 Kwonik": { fr: "2 Chroniques", es: "2 Crónicas" },
    "Esidras": { fr: "Esdras", es: "Esdras" },
    "Neemi": { fr: "Néhémie", es: "Nehemías" },
    "Estè": { fr: "Esther", es: "Ester" },
    "Jòb": { fr: "Job", es: "Job" },
    "Sòm": { fr: "Psaumes", es: "Salmos" },
    "Pwovèb": { fr: "Proverbes", es: "Proverbios" },
    "Eklezyas": { fr: "Ecclésiaste", es: "Eclesiastés" },
    "Chante Salomon": { fr: "Cantique des Cantiques", es: "Cantar de los Cantares" },
    "Ezayi": { fr: "Ésaïe", es: "Isaías" },
    "Jeremi": { fr: "Jérémie", es: "Jeremías" },
    "Lamantasyon": { fr: "Lamentations", es: "Lamentaciones" },
    "Ezekyèl": { fr: "Ézéchiel", es: "Ezequiel" },
    "Danyèl": { fr: "Daniel", es: "Daniel" },
    "Oze": { fr: "Osée", es: "Oseas" },
    "Jowèl": { fr: "Joël", es: "Joel" },
    "Amòs": { fr: "Amos", es: "Amós" },
    "Abdyas": { fr: "Abdias", es: "Abdías" },
    "Jonas": { fr: "Jonas", es: "Jonás" },
    "Miche": { fr: "Michée", es: "Miqueas" },
    "Nawoum": { fr: "Nahum", es: "Nahúm" },
    "Abakou": { fr: "Habacuc", es: "Habacuc" },
    "Sofoni": { fr: "Sophonie", es: "Sofonías" },
    "Aje": { fr: "Aggée", es: "Hageo" },
    "Zakari": { fr: "Zacharie", es: "Zacarías" },
    "Malachi": { fr: "Malachie", es: "Malaquías" },
    "Matye": { fr: "Matthieu", es: "Mateo" },
    "Mak": { fr: "Marc", es: "Marcos" },
    "Lik": { fr: "Luc", es: "Lucas" },
    "Jan": { fr: "Jean", es: "Juan" },
    "Travay": { fr: "Actes", es: "Hechos" },
    "Women": { fr: "Romains", es: "Romanos" },
    "1 Korent": { fr: "1 Corinthiens", es: "1 Corintios" },
    "2 Korent": { fr: "2 Corinthiens", es: "2 Corintios" },
    "Galat": { fr: "Galates", es: "Gálatas" },
    "Efez": { fr: "Éphésiens", es: "Efesios" },
    "Filip": { fr: "Philippiens", es: "Filipenses" },
    "Kolòs": { fr: "Colossiens", es: "Colosenses" },
    "1 Tesalonik": { fr: "1 Thessaloniciens", es: "1 Tesalonicenses" },
    "2 Tesalonik": { fr: "2 Thessaloniciens", es: "2 Tesalonicenses" },
    "1 Timote": { fr: "1 Timothée", es: "1 Timoteo" },
    "2 Timote": { fr: "2 Timothée", es: "2 Timoteo" },
    "Tid": { fr: "Tite", es: "Tito" },
    "Filemon": { fr: "Philémon", es: "Filemón" },
    "Ebre": { fr: "Hébreux", es: "Hebreos" },
    "Jak": { fr: "Jacques", es: "Santiago" },
    "1 Pyè": { fr: "1 Pierre", es: "1 Pedro" },
    "2 Pyè": { fr: "2 Pierre", es: "2 Pedro" },
    "1 Jan": { fr: "1 Jean", es: "1 Juan" },
    "2 Jan": { fr: "2 Jean", es: "2 Juan" },
    "3 Jan": { fr: "3 Jean", es: "3 Juan" },
    "Jid": { fr: "Jude", es: "Judas" },
    "Apokalips": { fr: "Apocalypse", es: "Apocalipsis" }
};

const categoryMapping = {
    "pentateuco": { ht: "Lwa / Pentatèk", fr: "Loi / Pentateuque", es: "Pentateuco" },
    "historia": { ht: "Istwa Izrayèl", fr: "Histoire d'Israël", es: "Historia" },
    "sabiduria": { ht: "Sajès ak Pwezi", fr: "Sagesse et Poésie", es: "Sabiduría" },
    "profetas-may": { ht: "Gwo Pwofèt yo", fr: "Grands Prophètes", es: "Profetas Mayores" },
    "profetas-men": { ht: "Ti Pwofèt yo", fr: "Petits Prophètes", es: "Profetas Menores" },
    "evangelios": { ht: "Bòn Nouvèl (Evanjil)", fr: "Évangiles", es: "Evangelios" },
    "hechos": { ht: "Travay Apòt yo", fr: "Actes des Apôtres", es: "Hechos" },
    "cartas-pablo": { ht: "Lèt Pòl yo", fr: "Épîtres de Paul", es: "Epístolas de Pablo" },
    "cartas-gen": { ht: "Lèt Jeneral yo", fr: "Épîtres Générales", es: "Epístolas Generales" },
    "apocalipsis": { ht: "Apokalips", fr: "Apocalypse", es: "Apocalipsis" },
    "personajes": { ht: "Pèsonaj", fr: "Personnages Bibliques", es: "Personajes" },
    "lugares": { ht: "Kote (Lye)", fr: "Lieux Bibliques", es: "Lugares" },
    "eventos": { ht: "Evènman", fr: "Événements Bibliques", es: "Eventos" },
    "temas": { ht: "Tèm", fr: "Thèmes Bibliques", es: "Temas" },
    "genesis": { ht: "Jenèz", fr: "Genèse", es: "Génesis" },
    "exodo": { ht: "Egzòd", fr: "Exode", es: "Éxodo" },
    "reyes": { ht: "Wa yo ak Pwofèt yo", fr: "Rois et Prophètes", es: "Reyes" },
    "salmos": { ht: "Sòm yo", fr: "Psaumes", es: "Salmos" },
    "milagros": { ht: "Mirak Jezi yo", fr: "Miracles de Jésus", es: "Milagros" },
    "parabolas": { ht: "Parabòl Jezi yo", fr: "Paraboles de Jésus", es: "Parábolas" },
    "mujeres": { ht: "Fanm nan Bib la", fr: "Femmes de la Bible", es: "Mujeres" },
    "personajes-at": { ht: "Pèsonaj Ansyen Testaman", fr: "Ancien Testament", es: "Personajes AT" },
    "personajes-nt": { ht: "Pèsonaj Nouvo Testaman", fr: "Nouveau Testament", es: "Personajes NT" },
    "doctrina": { ht: "Doktrin Biblik", fr: "Doctrine Biblique", es: "Doctrina" },
    "vida-cristiana": { ht: "Lavi Kretyen", fr: "Vie Chrétienne", es: "Vida Cristiana" },
    "iglesia": { ht: "Legliz", fr: "Église", es: "Iglesia" },
    "espiritu-santo": { ht: "Sentespri", fr: "Saint-Esprit", es: "Espíritu Santo" },
    "escatologia": { ht: "Eskatoloji", fr: "Eschatologie", es: "Escatología" },
    "mision": { ht: "Misyon", fr: "Mission", es: "Misión" },
    "ley-moral": { ht: "Lwa Moral", fr: "Loi Morale", es: "Ley Moral" },
    "nuevo-testamento": { ht: "Nouvo Testaman (Jeneral)", fr: "Nouveau Testament (Général)", es: "Nuevo Testamento" },
    "tabernakulo": { ht: "Tabènak ak Tanp", fr: "Tabernacle et Temple", es: "Tabernáculo" },
    "lideres": { ht: "Lidè nan Bib la", fr: "Leaders Bibliques", es: "Líderes" },
    "viajes-pablo": { ht: "Vwayaj Pòl yo", fr: "Voyages de Paul", es: "Viajes de Pablo" },
    "cultura": { ht: "Kilti ak Sosyete", fr: "Culture et Société", es: "Cultura" },
    "oracion": { ht: "Lapriyè", fr: "Prière", es: "Oración" },
    "at-general": { ht: "Ansyen Testaman (Jeneral)", fr: "Ancien Testament (Général)", es: "AT General" },
    "intertestamentario": { ht: "Peryòd Entètestamantè", fr: "Période Intertestamentaire", es: "Intertestamentario" },
    "guerras": { ht: "Lagè ak Batay", fr: "Guerres et Batailles", es: "Guerras" }
};

module.exports = { bookMapping, categoryMapping };
